name: Test Lighthouse Check with Minimum Score Enforcement
on:
  push:
    branch: [master]
  pull_request_target:
  pull_request:
    types: [opened, edited]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Lighthouse Check
        uses: foo-software/lighthouse-check-action@v2.0.5
        id: lighthouseCheck
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          urls: 'https://the-best-printers.vercel.app/'

      - name: Handle Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: '70'
          minBestPracticesScore: '70'
          minSeoScore: '70'
